from test import Test


all = [
    Test("blarg/cpu_instrs/01-special.gb", runtime=3.0),
    Test("blarg/cpu_instrs/02-interrupts.gb", runtime=1.0),
    Test("blarg/cpu_instrs/03-op sp,hl.gb", runtime=2.0),
    Test("blarg/cpu_instrs/04-op r,imm.gb", runtime=2.5),
    Test("blarg/cpu_instrs/05-op rp.gb", runtime=3.0),
    Test("blarg/cpu_instrs/06-ld r,r.gb", runtime=1.0),
    Test("blarg/cpu_instrs/07-jr,jp,call,ret,rst.gb", runtime=1.0),
    Test("blarg/cpu_instrs/08-misc instrs.gb", runtime=1.0),
    Test("blarg/cpu_instrs/09-op r,r.gb", runtime=7.0),
    Test("blarg/cpu_instrs/10-bit ops.gb", runtime=8.0),
    Test("blarg/cpu_instrs/11-op a,(hl).gb", runtime=10.0),

    Test("blarg/halt_bug.gb", runtime=2.0),
    Test("blarg/instr_timing.gb", runtime=1.0),
    Test("blarg/interrupt_time.gb", runtime=1.0),

    Test("blarg/mem_timing/01-read_timing.gb", runtime=1.0),
    Test("blarg/mem_timing/02-write_timing.gb", runtime=1.0),
    Test("blarg/mem_timing/03-modify_timing.gb", runtime=1.0),

    Test("blarg/mem_timing-2/01-read_timing.gb", runtime=1.0),
    Test("blarg/mem_timing-2/02-write_timing.gb", runtime=1.0),
    Test("blarg/mem_timing-2/03-modify_timing.gb", runtime=1.0),

    Test("blarg/oam_bug/1-lcd_sync.gb", runtime=1.0),
    Test("blarg/oam_bug/2-causes.gb", runtime=1.0),
    Test("blarg/oam_bug/3-non_causes.gb", runtime=1.0),
    Test("blarg/oam_bug/4-scanline_timing.gb", runtime=1.0),
    Test("blarg/oam_bug/5-timing_bug.gb", runtime=1.0),
    Test("blarg/oam_bug/6-timing_no_bug.gb", runtime=1.0),
    Test("blarg/oam_bug/7-timing_effect.gb", runtime=4.0),
    Test("blarg/oam_bug/8-instr_effect.gb", runtime=1.0),

    Test("blarg/dmg_sound/01-registers.gb", runtime=1.0),
    Test("blarg/dmg_sound/02-len ctr.gb", runtime=8.0),
    Test("blarg/dmg_sound/03-trigger.gb", runtime=1.0),
    Test("blarg/dmg_sound/04-sweep.gb", runtime=1.0),
    Test("blarg/dmg_sound/05-sweep details.gb", runtime=1.0),
    Test("blarg/dmg_sound/06-overflow on trigger.gb", runtime=1.0),
    Test("blarg/dmg_sound/07-len sweep period sync.gb", runtime=1.0),
    Test("blarg/dmg_sound/08-len ctr during power.gb", runtime=1.0),
    Test("blarg/dmg_sound/09-wave read while on.gb", runtime=1.0),
    Test("blarg/dmg_sound/10-wave trigger while on.gb", runtime=1.0),
    Test("blarg/dmg_sound/11-regs after power.gb", runtime=1.0),
    Test("blarg/dmg_sound/12-wave write while on.gb", runtime=1.0),

    Test("blarg/cgb_sound/01-registers.gb", runtime=1.0),
    Test("blarg/cgb_sound/02-len ctr.gb", runtime=6.0),
    Test("blarg/cgb_sound/03-trigger.gb", runtime=13.0),
    Test("blarg/cgb_sound/04-sweep.gb", runtime=1.0),
    Test("blarg/cgb_sound/05-sweep details.gb", runtime=1.0),
    Test("blarg/cgb_sound/06-overflow on trigger.gb", runtime=1.0),
    Test("blarg/cgb_sound/07-len sweep period sync.gb", runtime=1.0),
    Test("blarg/cgb_sound/08-len ctr during power.gb", runtime=1.0),
    Test("blarg/cgb_sound/09-wave read while on.gb", runtime=1.0),
    Test("blarg/cgb_sound/10-wave trigger while on.gb", runtime=1.0),
    Test("blarg/cgb_sound/11-regs after power.gb", runtime=1.0),
    Test("blarg/cgb_sound/12-wave.gb", runtime=1.0),
]
