from test import Test


all = [
    Test("mooneye/acceptance/add_sp_e_timing.gb", runtime=1.5),
    Test("mooneye/acceptance/bits/mem_oam.gb", runtime=1.5),
    Test("mooneye/acceptance/bits/reg_f.gb", runtime=1.5),
    Test("mooneye/acceptance/bits/unused_hwio-GS.gb", runtime=1.5),
    # Test("mooneye/acceptance/boot_div-dmg0.gb", runtime=5.5),
    Test("mooneye/acceptance/boot_div-dmgABCmgb.gb", runtime=1.5),
    # Test("mooneye/acceptance/boot_div-S.gb", runtime=1.5),
    # Test("mooneye/acceptance/boot_div2-S.gb", runtime=1.5),
    # Test("mooneye/acceptance/boot_hwio-dmg0.gb", runtime=1.5),
    Test("mooneye/acceptance/boot_hwio-dmgABCmgb.gb", runtime=1.5),
    # Test("mooneye/acceptance/boot_hwio-S.gb", runtime=1.5),
    # Test("mooneye/acceptance/boot_regs-dmg0.gb", runtime=1.5),
    Test("mooneye/acceptance/boot_regs-dmgABC.gb", runtime=1.5),
    # Test("mooneye/acceptance/boot_regs-mgb.gb", runtime=1.5),
    # Test("mooneye/acceptance/boot_regs-sgb.gb", runtime=1.5),
    # Test("mooneye/acceptance/boot_regs-sgb2.gb", runtime=1.5),
    Test("mooneye/acceptance/call_cc_timing.gb", runtime=1.5),
    Test("mooneye/acceptance/call_cc_timing2.gb", runtime=1.5),
    Test("mooneye/acceptance/call_timing.gb", runtime=1.5),
    Test("mooneye/acceptance/call_timing2.gb", runtime=1.5),
    Test("mooneye/acceptance/div_timing.gb", runtime=1.5),
    Test("mooneye/acceptance/di_timing-GS.gb", runtime=1.5),
    Test("mooneye/acceptance/ei_sequence.gb", runtime=1.5),
    Test("mooneye/acceptance/ei_timing.gb", runtime=1.5),
    Test("mooneye/acceptance/halt_ime0_ei.gb", runtime=1.5),
    Test("mooneye/acceptance/halt_ime0_nointr_timing.gb", runtime=1.5),
    Test("mooneye/acceptance/halt_ime1_timing.gb", runtime=1.5),
    Test("mooneye/acceptance/halt_ime1_timing2-GS.gb", runtime=1.5),
    Test("mooneye/acceptance/if_ie_registers.gb", runtime=1.5),
    Test("mooneye/acceptance/instr/daa.gb", runtime=1.5),
    Test("mooneye/acceptance/interrupts/ie_push.gb", runtime=1.5),
    Test("mooneye/acceptance/intr_timing.gb", runtime=1.5),
    Test("mooneye/acceptance/jp_cc_timing.gb", runtime=1.5),
    Test("mooneye/acceptance/jp_timing.gb", runtime=1.5),
    Test("mooneye/acceptance/ld_hl_sp_e_timing.gb", runtime=1.5),
    Test("mooneye/acceptance/oam_dma/basic.gb", runtime=1.5),
    Test("mooneye/acceptance/oam_dma/reg_read.gb", runtime=1.5),
    Test("mooneye/acceptance/oam_dma/sources-GS.gb", runtime=1.5),
    Test("mooneye/acceptance/oam_dma_restart.gb", runtime=1.5),
    Test("mooneye/acceptance/oam_dma_start.gb", runtime=1.5),
    Test("mooneye/acceptance/oam_dma_timing.gb", runtime=1.5),
    Test("mooneye/acceptance/pop_timing.gb", runtime=1.5),
    Test("mooneye/acceptance/ppu/hblank_ly_scx_timing-GS.gb", runtime=1.5),
    Test("mooneye/acceptance/ppu/intr_1_2_timing-GS.gb", runtime=1.5),
    Test("mooneye/acceptance/ppu/intr_2_0_timing.gb", runtime=1.5),
    Test("mooneye/acceptance/ppu/intr_2_mode0_timing.gb", runtime=1.5),
    Test("mooneye/acceptance/ppu/intr_2_mode0_timing_sprites.gb", runtime=5.5),
    Test("mooneye/acceptance/ppu/intr_2_mode3_timing.gb", runtime=1.5),
    Test("mooneye/acceptance/ppu/intr_2_oam_ok_timing.gb", runtime=1.5),
    Test("mooneye/acceptance/ppu/lcdon_timing-GS.gb", runtime=1.5),
    Test("mooneye/acceptance/ppu/lcdon_write_timing-GS.gb", runtime=2.0),
    Test("mooneye/acceptance/ppu/stat_irq_blocking.gb", runtime=1.5),
    Test("mooneye/acceptance/ppu/stat_lyc_onoff.gb", runtime=1.5),
    Test("mooneye/acceptance/ppu/vblank_stat_intr-GS.gb", runtime=1.5),
    Test("mooneye/acceptance/push_timing.gb", runtime=1.5),
    Test("mooneye/acceptance/rapid_di_ei.gb", runtime=1.5),
    Test("mooneye/acceptance/reti_intr_timing.gb", runtime=1.5),
    Test("mooneye/acceptance/reti_timing.gb", runtime=1.5),
    Test("mooneye/acceptance/ret_cc_timing.gb", runtime=1.5),
    Test("mooneye/acceptance/ret_timing.gb", runtime=1.5),
    Test("mooneye/acceptance/rst_timing.gb", runtime=1.5),
    Test("mooneye/acceptance/serial/boot_sclk_align-dmgABCmgb.gb", runtime=1.5),
    Test("mooneye/acceptance/timer/div_write.gb", runtime=1.5),
    Test("mooneye/acceptance/timer/rapid_toggle.gb", runtime=1.5),
    Test("mooneye/acceptance/timer/tim00.gb", runtime=1.5),
    Test("mooneye/acceptance/timer/tim00_div_trigger.gb", runtime=1.5),
    Test("mooneye/acceptance/timer/tim01.gb", runtime=1.5),
    Test("mooneye/acceptance/timer/tim01_div_trigger.gb", runtime=1.5),
    Test("mooneye/acceptance/timer/tim10.gb", runtime=1.5),
    Test("mooneye/acceptance/timer/tim10_div_trigger.gb", runtime=1.5),
    Test("mooneye/acceptance/timer/tim11.gb", runtime=1.5),
    Test("mooneye/acceptance/timer/tim11_div_trigger.gb", runtime=1.5),
    Test("mooneye/acceptance/timer/tima_reload.gb", runtime=1.5),
    Test("mooneye/acceptance/timer/tima_write_reloading.gb", runtime=1.5),
    Test("mooneye/acceptance/timer/tma_write_reloading.gb", runtime=1.5),

    Test("mooneye/emulator-only/mbc1/bits_bank1.gb", runtime=3.5),
    Test("mooneye/emulator-only/mbc1/bits_bank2.gb", runtime=3.5),
    Test("mooneye/emulator-only/mbc1/bits_mode.gb", runtime=4.5),
    Test("mooneye/emulator-only/mbc1/bits_ramg.gb", runtime=6.5),
    Test("mooneye/emulator-only/mbc1/multicart_rom_8Mb.gb", runtime=1.0),
    Test("mooneye/emulator-only/mbc1/ram_256kb.gb", runtime=1.5),
    Test("mooneye/emulator-only/mbc1/ram_64kb.gb", runtime=1.5),
    Test("mooneye/emulator-only/mbc1/rom_16Mb.gb", runtime=1.5),
    Test("mooneye/emulator-only/mbc1/rom_1Mb.gb", runtime=1.5),
    Test("mooneye/emulator-only/mbc1/rom_2Mb.gb", runtime=1.5),
    Test("mooneye/emulator-only/mbc1/rom_4Mb.gb", runtime=1.5),
    Test("mooneye/emulator-only/mbc1/rom_512kb.gb", runtime=1.5),
    Test("mooneye/emulator-only/mbc1/rom_8Mb.gb", runtime=1.5),

    Test("mooneye/emulator-only/mbc2/bits_ramg.gb", runtime=7.5),
    Test("mooneye/emulator-only/mbc2/bits_romb.gb", runtime=4.0),
    Test("mooneye/emulator-only/mbc2/bits_unused.gb", runtime=3.5),
    Test("mooneye/emulator-only/mbc2/ram.gb", runtime=1.5),
    Test("mooneye/emulator-only/mbc2/rom_1Mb.gb", runtime=1.5),
    Test("mooneye/emulator-only/mbc2/rom_2Mb.gb", runtime=1.5),
    Test("mooneye/emulator-only/mbc2/rom_512kb.gb", runtime=1.5),

    Test("mooneye/emulator-only/mbc5/rom_16Mb.gb", runtime=1.5),
    Test("mooneye/emulator-only/mbc5/rom_1Mb.gb", runtime=1.5),
    Test("mooneye/emulator-only/mbc5/rom_2Mb.gb", runtime=1.5),
    Test("mooneye/emulator-only/mbc5/rom_32Mb.gb", runtime=1.5),
    Test("mooneye/emulator-only/mbc5/rom_4Mb.gb", runtime=1.5),
    Test("mooneye/emulator-only/mbc5/rom_512kb.gb", runtime=1.5),
    Test("mooneye/emulator-only/mbc5/rom_64Mb.gb", runtime=1.5),
    Test("mooneye/emulator-only/mbc5/rom_8Mb.gb", runtime=1.5),

    Test("mooneye/manual-only/sprite_priority.gb", runtime=1.5),

    # Test("mooneye/misc/bits/unused_hwio-C.gb", runtime=1.5),
    # Test("mooneye/misc/boot_div-A.gb", runtime=1.5),
    # Test("mooneye/misc/boot_div-cgb0.gb", runtime=1.5, gbc=True),
    Test("mooneye/misc/boot_div-cgbABCDE.gb", runtime=1.5, gbc=True),
    # Test("mooneye/misc/boot_hwio-C.gb", runtime=1.5),
    # Test("mooneye/misc/boot_regs-A.gb", runtime=1.5),
    Test("mooneye/misc/boot_regs-cgb.gb", runtime=1.5, gbc=True),
    # Test("mooneye/misc/ppu/vblank_stat_intr-C.gb", runtime=1.5),
]
